[workspace]
members = ["boot", "qemu"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
opt-level = 3
strip = true

[profile.release.package.boot]
opt-level = "z" # Since we're limited to 510 bytes, we need to be as small as possible
