cargo-features = ["per-package-target"]

[package]
name = "boot"
version = "0.1.0"
edition = "2021"
default-target = "x86_64-unknown-none"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
